# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    toolbars:
        configs:
            post_toolbar: [
                ['Cut', 'Copy', 'Paste', 'PasteText', 'Undo', 'Redo']
                ['Table', 'HorizontalRule', 'SpecialChar'],
                '@standard.tools',
                '@standard.basic_styles',
                ['NumberedList', 'BulletedList', '-', 'Blockquote'],
                ['Format', 'FontSize', 'TextColor', 'BGColor'],
            ]